apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-deployment
  labels:
    app: app-pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pay
  template:
    metadata:
      labels:
        app: app-pay
    spec:
      containers:
      - name: app-pay
        image: nelsonq2424/app-pay
        ports:
        - containerPort: 8010