apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-config-deploy
  labels:
   app: app-config
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  replicas: 6
  selector:
    matchLabels:
         app: app-config
  template:
    metadata:
      labels:
        app: app-config
    spec:
     containers:
     - name: app-config-container
       image: 'nelsonq2424/app-config'
       ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
 name: app-config-service
 labels:
  app: app-config
spec:
 type: NodePort
 selector:
  app: app-config
 ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: http