apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
  namespace: parcial2
  labels:
    app: app-invoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-invoice
  template:
    metadata:
      labels:
        app: app-invoice
    spec:
      containers:
      - name: app-invoice
        image: nelsonq2424/app-invoice
        ports:
        - containerPort: 8006

---
apiVersion: v1
kind: Service
metadata:
 name: app-invoice-service
 namespace: parcial2
 labels:
  app: app-invoice
spec:
 type: LoadBalancer
 selector:
  app: app-invoice
 ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    name: http